name: 'gitboard.io'
description: 'Provides job information to gittboard.io. gitboard.io makes GitHub Actions made visible, providing a real time build status dashboard for GitHub Actions.'
inputs:
  username:
    description: 'gitboard.io account username'
    required: true
  key:
    description: 'gitboard.io account key'
    required: true
  status:
    description: 'job status'
    default: ${{ job.status }}
  steps:
    description: 'job'
    default: ${{ job }}
runs:
  using: 'node16'
  pre: 'pre/index.js'
  main: 'main/index.js'
  post: 'post/index.js'
