name: 'gitboard.io'
description: 'Provides job information to gittboard.io. gitboard.io makes GitHub Actions made visible, providing a real time build status dashboard for GitHub Actions.'
inputs:
  username:
    description: 'gitboard.io account username'
    required: true
  key:
    description: 'gitboard.io account key'
    required: true
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'build/index.js'