name: 'Update gitboard.io Dashboard'
description: 'Sends job status information to gittboard.io. gitboard.io makes GitHub Actions visible, providing a build status dashboard.'
branding:
  icon: grid
  color: gray-dark
inputs:
  username:
    description: 'gitboard.io account username'
    required: true
  key:
    description: 'gitboard.io account key'
    required: true
  status:
    description: 'job status'
    default: ${{ job.status }}
runs:
  using: 'node16'
  pre: 'pre/index.js'
  main: 'main/index.js'
  post: 'post/index.js'
